image: alpine:latest

variables:
  CI_TRON_TEMPLATE_PROJECT: &ci-tron-template-project postmarketOS/ci-common
  CI_TRON_JOB_TEMPLATE_PROJECT_URL: $CI_SERVER_URL/$CI_TRON_TEMPLATE_PROJECT
  CI_TRON_JOB_TEMPLATE_COMMIT: &ci-tron-template-commit 7c95b5f2d53533e8722abf57c73e558168e811f3

include:
  - project: *ci-tron-template-project
    ref: *ci-tron-template-commit
    file: '/ci-tron/common.yml'

stages:
  - unit tests
  - integration tests
  - hardware tests

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: '$CI_COMMIT_TAG != null'

unit tests:
  stage: unit tests
  before_script:
    - adduser -D build
  script:
    - .ci/run.sh
  artifacts:
    expire_in: 1 week

integration test:
  stage: integration tests
  before_script:
    - apk add curl android-tools file
    - apk add --allow-untrusted -X http://mirror.postmarketos.org/postmarketos/master/ mkbootimg-osm0sis
    # Force IPv4 for gitlab.postmarketos.org until it supports IPv6 too, OSUOSL is
    # working on it (infra#195)
    - "echo '140.211.167.182 gitlab.postmarketos.org' >> /etc/hosts"
    - curl -4fsSL "https://gitlab.postmarketos.org/postmarketOS/ci-common/-/raw/master/install_pmbootstrap.sh" | sh
    - su pmos -c "pmbootstrap config device ${DEVICE}"
    - su pmos -c "pmbootstrap config ui none"
  script:
    - su pmos -c .ci/integration_test.sh
  after_script:
    - cp /home/pmos/.local/var/pmbootstrap/log.txt $CI_PROJECT_DIR
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - log.txt
      - work/
      - boot/
      - bootimg_extract/
  parallel:
    # NOTE: the pinephone isn't here because boot-deploy is pretty much just a nop
    # on that device.
    matrix:
      # Android device with appended DTB and standard boot.img
      - DEVICE: oneplus-enchilada
      # Chromebook with depthcharge image (creates /boot/vmlinuz.kpart)
      - DEVICE: google-veyron
      # ThinkPad x13s generates systemd-boot config
      - DEVICE: lenovo-21bx
      # Another standard Android device, but an msm8916 one
      - DEVICE: samsung-a5
      # Android device with a boot.img containing an exynos QCDT image
      - DEVICE: samsung-on7xelte
      # extlinux
      - DEVICE: pine64-pinebookpro
      # sd-boot + CPU microcode config
      - DEVICE: generic-x86_64

build-ci-tron-qemu-amd64:
  stage: hardware tests
  extends:
    - .pmos-ci-tron-build-boot-artifacts
  variables:
    DEVICE_NAME: qemu-amd64
    KERNEL_VARIANT: lts
    INSTALL_PACKAGES: device-${DEVICE_NAME} device-${DEVICE_NAME}-kernel-${KERNEL_VARIANT} postmarketos-mkinitfs-hook-ci
  before_script:
    - mkdir -p rootfs/usr/bin
    - cp boot-deploy rootfs/usr/bin
    - mkdir -p rootfs/usr/share/boot-deploy
    - cp boot-deploy-functions.sh rootfs/usr/share/boot-deploy

test-ci-tron-qemu-amd64:
  stage: hardware tests
  extends:
    - .pmos-ci-tron-initramfs-test
    - .pmos-ci-tron-runner-qemu-amd64
  dependencies: []
  needs:
    - job: 'build-ci-tron-qemu-amd64'
      artifacts: false
  variables:
    CI_TRON_KERNEL__URL: "glartifact://build-ci-tron-qemu-amd64/${CI_TRON__PMB_EXPORT_PATH}/vmlinuz-${KERNEL_VARIANT}"
    CI_TRON_INITRAMFS__INITRAMFS__URL: "glartifact://build-ci-tron-qemu-amd64/${CI_TRON__PMB_EXPORT_PATH}/initramfs"
    CI_TRON_KERNEL_CMDLINE__DEVICEINFO: 'console=tty1 console=ttyS0,115200 PMOS_FORCE_PARTITION_RESIZE'
    DEVICE_NAME: qemu-amd64
    KERNEL_VARIANT: lts
