#!/bin/sh
# Copyright 2021 Clayton Craft <clayton@craftyguy.net>
# SPDX-License-Identifier: GPL-3.0-or-later
set -eu

initfs_filename=""
input_dir=""
output_dir=""
additional_files=""

functions_file=${BOOT_DEPLOY_FUNCTIONS:-/usr/share/boot-deploy/boot-deploy-functions.sh}
if [ ! -f "$functions_file" ]; then
	echo "ERROR: functions file not found: $functions_file"
	exit 1
fi

# shellcheck disable=SC1090
. "$functions_file"

get_options "$@"
source_deviceinfo
source_boot_deploy_config
append_or_copy_dtb
add_mtk_header
create_uboot_files
create_bootimg
create_depthcharge_kernel_image

mkdir -p "$output_dir"

files_to_copy="$input_dir/$initfs_filename"
for f in $additional_files; do
	files_to_copy="$files_to_copy $input_dir/$f"
done

check_destination_free_space "$files_to_copy"

# copy files to destination
for f in $files_to_copy; do
	filename="$(basename "$f")"
	echo "==> Installing: $output_dir/$filename"
	copy "$f" "$output_dir/$filename"
done

sync

# flashing requires things in /boot to exist
flash_updated_boot_parts
flash_updated_depthcharge_kernel

exit 0
